import { Component, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup } from "@angular/forms";
import { ExcelExportData } from '@progress/kendo-angular-excel-export';
import { GridComponent } from '@progress/kendo-angular-grid';
import { process } from "@progress/kendo-data-query";
import { Portfolio } from 'src/app/core/model/portfolio';

@Component({
  selector: 'gt-portfolios-grid',
  templateUrl: './portfolios-grid.component.html',
  styleUrls: ['./portfolios-grid.component.scss']
})
export class PortfoliosGridComponent {

  @ViewChild('portfolioGrid') portfolioGrid: GridComponent;
  public formGroup: FormGroup;
  viewOptions = [
    { value: 1, text: 'View 1' },
    { value: 2, text: 'View 2' },
    { value: 3, text: 'View 3' },
  ];
  itemButton = { text: 'New deal' };
  portfolioData: Portfolio[] = [
    {
      id: 1039,
      status: 'Confirmed',
      name: 'IC Loan 3',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -400993.21,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 18),
      term: '5y',
      end: new Date(2027, 1, 18),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 204389,
      status: 'Created',
      name: 'Interim 5',
      type: 'Loan/Deposit',
      product: 'Loan/D 1',
      amount: 20872.77,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 16),
      term: '1y',
      end: new Date(2023, 6, 16),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2934904,
      status: 'Created',
      name: 'BOFA Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 15),
      term: '5y',
      end: new Date(2027, 6, 15),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 10389,
      status: 'Submitted',
      name: 'IC Loan 2',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298826.33,
      currency: 'USD',
      attachments: 3,
      start: new Date(2022, 6, 14),
      term: '1y',
      end: new Date(2027, 6, 14),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 385,
      status: 'Confirmed',
      name: 'Oil purchase',
      type: 'Loan/Deposit',
      product: 'Loan/D 4',
      amount: 9102.0,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 11),
      term: '2y',
      end: new Date(2024, 6, 11),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 22,
      status: 'Confirmed',
      name: 'Commitment fee',
      type: 'Facility Fee',
      product: 'FAC122',
      amount: 209881.76,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 10),
      term: '6m',
      end: new Date(2022, 12, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 349,
      status: 'Confirmed',
      name: '2022 TLA Actual',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 21.99,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 10),
      term: '3m',
      end: new Date(2022, 9, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 2199,
      status: 'Submitted',
      name: 'IC Loan 4',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -14298.0,
      currency: 'USD',
      attachments: 8,
      start: new Date(2022, 6, 9),
      term: '5y',
      end: new Date(2027, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 3030,
      status: 'Created',
      name: 'IC Loan 5',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -222000.0,
      currency: 'USD',
      attachments: 11,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 1010,
      status: 'Confirmed',
      name: '2022 IR swap',
      type: 'IR Swap',
      product: 'IRSWAP_1',
      amount: -400993.21,
      currency: 'EUR',
      attachments: 3,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 3999,
      status: 'Submitted',
      name: 'IC Loan 6',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 2',
      amount: 12391.0,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '3m',
      end: new Date(2022, 9, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 29388,
      status: 'Created',
      name: 'Interim 7',
      type: 'Loan/Deposit',
      product: 'DEPO_3',
      amount: 20872.77,
      currency: 'EUR',
      attachments: 4,
      start: new Date(2022, 6, 8),
      term: '6m',
      end: new Date(2022, 12, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 2837,
      status: 'Confirmed',
      name: 'JPMC Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '1y',
      end: new Date(2023, 6, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 11,
      status: 'Created',
      name: 'IC Loan 8',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298926.33,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 7),
      term: '2y',
      end: new Date(2024, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 15,
      status: 'Confirmed',
      name: '2021 IR Swap',
      type: 'IR Swap',
      product: 'IRSWAP_2',
      amount: 94102.0,
      currency: 'EUR',
      attachments: 6,
      start: new Date(2022, 6, 7),
      term: '5y',
      end: new Date(2027, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 19,
      status: 'Confirmed',
      name: '2021 TLA Actual',
      type: 'Facility Fee',
      product: 'FAC_1',
      amount: 209881.76,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 922,
      status: 'Created',
      name: 'BOFA 19',
      type: 'Loan/Deposit',
      product: 'Loan 4',
      amount: 42.87,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 142,
      status: 'Submitted',
      name: 'Test deal',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: 1567.08,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '6m',
      end: new Date(2022, 12, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 290,
      status: 'Confirmed',
      name: 'VAN 2021',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: 18902.74,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 6),
      term: '1y',
      end: new Date(2023, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 431,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: -278899.27,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 6),
      term: '2y',
      end: new Date(2024, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 525,
      status: 'Confirmed',
      name: 'IC Loan 10',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -10367.89,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 30),
      term: '53',
      end: new Date(2025, 5, 30),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 6666,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'IR Swap',
      product: 'IRSWAP_3',
      amount: 45982.88,
      currency: 'USD',
      attachments: 2,
      start: new Date(2022, 5, 28),
      term: '5y',
      end: new Date(2027, 5, 28),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 724,
      status: 'Created',
      name: 'VAN Borrowing',
      type: 'Loan/Deposit',
      product: 'DEPO_2',
      amount: 300000.00,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 27),
      term: '6m',
      end: new Date(2022, 11, 27),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 31233,
      status: 'Confirmed',
      name: 'TBD',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 12276.29,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 5, 26),
      term: '3m',
      end: new Date(2022, 8, 26),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 5225,
      status: 'Confirmed',
      name: 'Test deal',
      type: 'Loan/Deposit',
      product: 'DEPO_MAIN',
      amount: 3637.39,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 5, 24),
      term: '1y',
      end: new Date(2023, 5, 24),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2100,
      status: 'Confirmed',
      name: 'IC Loan 3',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -400993.21,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 18),
      term: '5y',
      end: new Date(2027, 1, 18),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 3234,
      status: 'Created',
      name: 'Interim 5',
      type: 'Loan/Deposit',
      product: 'Loan/D 1',
      amount: 20872.77,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 16),
      term: '1y',
      end: new Date(2023, 6, 16),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 4422,
      status: 'Created',
      name: 'BOFA Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 15),
      term: '5y',
      end: new Date(2027, 6, 15),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 163,
      status: 'Submitted',
      name: 'IC Loan 2',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298826.33,
      currency: 'USD',
      attachments: 3,
      start: new Date(2022, 6, 14),
      term: '1y',
      end: new Date(2027, 6, 14),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 7,
      status: 'Confirmed',
      name: 'Oil purchase',
      type: 'Loan/Deposit',
      product: 'Loan/D 4',
      amount: 9102.0,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 11),
      term: '2y',
      end: new Date(2024, 6, 11),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 193,
      status: 'Confirmed',
      name: 'Commitment fee',
      type: 'Facility Fee',
      product: 'FAC122',
      amount: 209881.76,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 10),
      term: '6m',
      end: new Date(2022, 12, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 234245,
      status: 'Confirmed',
      name: '2022 TLA Actual',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 21.99,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 10),
      term: '3m',
      end: new Date(2022, 9, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 810,
      status: 'Submitted',
      name: 'IC Loan 4',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -14298.0,
      currency: 'USD',
      attachments: 8,
      start: new Date(2022, 6, 9),
      term: '5y',
      end: new Date(2027, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 10966,
      status: 'Created',
      name: 'IC Loan 5',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -222000.0,
      currency: 'USD',
      attachments: 11,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 175333,
      status: 'Confirmed',
      name: '2022 IR swap',
      type: 'IR Swap',
      product: 'IRSWAP_1',
      amount: -400993.21,
      currency: 'EUR',
      attachments: 3,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 2337,
      status: 'Submitted',
      name: 'IC Loan 6',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 2',
      amount: 12391.0,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '3m',
      end: new Date(2022, 9, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 258,
      status: 'Created',
      name: 'Interim 7',
      type: 'Loan/Deposit',
      product: 'DEPO_3',
      amount: 20872.77,
      currency: 'EUR',
      attachments: 4,
      start: new Date(2022, 6, 8),
      term: '6m',
      end: new Date(2022, 12, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 3554,
      status: 'Confirmed',
      name: 'JPMC Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '1y',
      end: new Date(2023, 6, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 8444,
      status: 'Created',
      name: 'IC Loan 8',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298926.33,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 7),
      term: '2y',
      end: new Date(2024, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2038,
      status: 'Confirmed',
      name: '2021 IR Swap',
      type: 'IR Swap',
      product: 'IRSWAP_2',
      amount: 94102.0,
      currency: 'EUR',
      attachments: 6,
      start: new Date(2022, 6, 7),
      term: '5y',
      end: new Date(2027, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 449,
      status: 'Confirmed',
      name: '2021 TLA Actual',
      type: 'Facility Fee',
      product: 'FAC_1',
      amount: 209881.76,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 25252,
      status: 'Created',
      name: 'BOFA 19',
      type: 'Loan/Deposit',
      product: 'Loan 4',
      amount: 42.87,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 14253,
      status: 'Submitted',
      name: 'Test deal',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: 1567.08,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '6m',
      end: new Date(2022, 12, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 29712,
      status: 'Confirmed',
      name: 'VAN 2021',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: 18902.74,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 6),
      term: '1y',
      end: new Date(2023, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 43163,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: -278899.27,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 6),
      term: '2y',
      end: new Date(2024, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 52489,
      status: 'Confirmed',
      name: 'IC Loan 10',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -10367.89,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 30),
      term: '53',
      end: new Date(2025, 5, 30),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 6643,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'IR Swap',
      product: 'IRSWAP_3',
      amount: 45982.88,
      currency: 'USD',
      attachments: 2,
      start: new Date(2022, 5, 28),
      term: '5y',
      end: new Date(2027, 5, 28),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 72466,
      status: 'Created',
      name: 'VAN Borrowing',
      type: 'Loan/Deposit',
      product: 'DEPO_2',
      amount: 300000.00,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 27),
      term: '6m',
      end: new Date(2022, 11, 27),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 312423,
      status: 'Confirmed',
      name: 'TBD',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 12276.29,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 5, 26),
      term: '3m',
      end: new Date(2022, 8, 26),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 535235,
      status: 'Confirmed',
      name: 'Test deal',
      type: 'Loan/Deposit',
      product: 'DEPO_MAIN',
      amount: 3637.39,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 5, 24),
      term: '1y',
      end: new Date(2023, 5, 24),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 216574,
      status: 'Confirmed',
      name: 'IC Loan 3',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -400993.21,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 18),
      term: '5y',
      end: new Date(2027, 1, 18),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 32346,
      status: 'Created',
      name: 'Interim 5',
      type: 'Loan/Deposit',
      product: 'Loan/D 1',
      amount: 20872.77,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 16),
      term: '1y',
      end: new Date(2023, 6, 16),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 44346,
      status: 'Created',
      name: 'BOFA Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 15),
      term: '5y',
      end: new Date(2027, 6, 15),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 16253,
      status: 'Submitted',
      name: 'IC Loan 2',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298826.33,
      currency: 'USD',
      attachments: 3,
      start: new Date(2022, 6, 14),
      term: '1y',
      end: new Date(2027, 6, 14),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 7457,
      status: 'Confirmed',
      name: 'Oil purchase',
      type: 'Loan/Deposit',
      product: 'Loan/D 4',
      amount: 9102.0,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 11),
      term: '2y',
      end: new Date(2024, 6, 11),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 1953,
      status: 'Confirmed',
      name: 'Commitment fee',
      type: 'Facility Fee',
      product: 'FAC122',
      amount: 209881.76,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 10),
      term: '6m',
      end: new Date(2022, 12, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2211,
      status: 'Confirmed',
      name: '2022 TLA Actual',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 21.99,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 10),
      term: '3m',
      end: new Date(2022, 9, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 8115,
      status: 'Submitted',
      name: 'IC Loan 4',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -14298.0,
      currency: 'USD',
      attachments: 8,
      start: new Date(2022, 6, 9),
      term: '5y',
      end: new Date(2027, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 1043659,
      status: 'Created',
      name: 'IC Loan 5',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -222000.0,
      currency: 'USD',
      attachments: 11,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 14367,
      status: 'Confirmed',
      name: '2022 IR swap',
      type: 'IR Swap',
      product: 'IRSWAP_1',
      amount: -400993.21,
      currency: 'EUR',
      attachments: 3,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 627,
      status: 'Submitted',
      name: 'IC Loan 6',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 2',
      amount: 12391.0,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '3m',
      end: new Date(2022, 9, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 628,
      status: 'Created',
      name: 'Interim 7',
      type: 'Loan/Deposit',
      product: 'DEPO_3',
      amount: 20872.77,
      currency: 'EUR',
      attachments: 4,
      start: new Date(2022, 6, 8),
      term: '6m',
      end: new Date(2022, 12, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 346,
      status: 'Confirmed',
      name: 'JPMC Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '1y',
      end: new Date(2023, 6, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 844,
      status: 'Created',
      name: 'IC Loan 8',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298926.33,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 7),
      term: '2y',
      end: new Date(2024, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 234560,
      status: 'Confirmed',
      name: '2021 IR Swap',
      type: 'IR Swap',
      product: 'IRSWAP_2',
      amount: 94102.0,
      currency: 'EUR',
      attachments: 6,
      start: new Date(2022, 6, 7),
      term: '5y',
      end: new Date(2027, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 946,
      status: 'Confirmed',
      name: '2021 TLA Actual',
      type: 'Facility Fee',
      product: 'FAC_1',
      amount: 209881.76,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 663,
      status: 'Created',
      name: 'BOFA 19',
      type: 'Loan/Deposit',
      product: 'Loan 4',
      amount: 42.87,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 5514,
      status: 'Submitted',
      name: 'Test deal',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: 1567.08,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '6m',
      end: new Date(2022, 12, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 629,
      status: 'Confirmed',
      name: 'VAN 2021',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: 18902.74,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 6),
      term: '1y',
      end: new Date(2023, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 466663,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: -278899.27,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 6),
      term: '2y',
      end: new Date(2024, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 5542,
      status: 'Confirmed',
      name: 'IC Loan 10',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -10367.89,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 30),
      term: '53',
      end: new Date(2025, 5, 30),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 6256,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'IR Swap',
      product: 'IRSWAP_3',
      amount: 45982.88,
      currency: 'USD',
      attachments: 2,
      start: new Date(2022, 5, 28),
      term: '5y',
      end: new Date(2027, 5, 28),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 7082,
      status: 'Created',
      name: 'VAN Borrowing',
      type: 'Loan/Deposit',
      product: 'DEPO_2',
      amount: 300000.00,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 27),
      term: '6m',
      end: new Date(2022, 11, 27),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 36601,
      status: 'Confirmed',
      name: 'TBD',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 12276.29,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 5, 26),
      term: '3m',
      end: new Date(2022, 8, 26),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 9885,
      status: 'Confirmed',
      name: 'Test deal',
      type: 'Loan/Deposit',
      product: 'DEPO_MAIN',
      amount: 3637.39,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 5, 24),
      term: '1y',
      end: new Date(2023, 5, 24),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2581,
      status: 'Confirmed',
      name: 'IC Loan 3',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -400993.21,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 18),
      term: '5y',
      end: new Date(2027, 1, 18),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 32,
      status: 'Created',
      name: 'Interim 5',
      type: 'Loan/Deposit',
      product: 'Loan/D 1',
      amount: 20872.77,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 16),
      term: '1y',
      end: new Date(2023, 6, 16),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 333334,
      status: 'Created',
      name: 'BOFA Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 15),
      term: '5y',
      end: new Date(2027, 6, 15),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 136,
      status: 'Submitted',
      name: 'IC Loan 2',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298826.33,
      currency: 'USD',
      attachments: 3,
      start: new Date(2022, 6, 14),
      term: '1y',
      end: new Date(2027, 6, 14),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 45,
      status: 'Confirmed',
      name: 'Oil purchase',
      type: 'Loan/Deposit',
      product: 'Loan/D 4',
      amount: 9102.0,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 11),
      term: '2y',
      end: new Date(2024, 6, 11),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 47,
      status: 'Confirmed',
      name: 'Commitment fee',
      type: 'Facility Fee',
      product: 'FAC122',
      amount: 209881.76,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 10),
      term: '6m',
      end: new Date(2022, 12, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 22112,
      status: 'Confirmed',
      name: '2022 TLA Actual',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 21.99,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 10),
      term: '3m',
      end: new Date(2022, 9, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 81432,
      status: 'Submitted',
      name: 'IC Loan 4',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -14298.0,
      currency: 'USD',
      attachments: 8,
      start: new Date(2022, 6, 9),
      term: '5y',
      end: new Date(2027, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 11409,
      status: 'Created',
      name: 'IC Loan 5',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -222000.0,
      currency: 'USD',
      attachments: 11,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 11247,
      status: 'Confirmed',
      name: '2022 IR swap',
      type: 'IR Swap',
      product: 'IRSWAP_1',
      amount: -400993.21,
      currency: 'EUR',
      attachments: 3,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 27347,
      status: 'Submitted',
      name: 'IC Loan 6',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 2',
      amount: 12391.0,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '3m',
      end: new Date(2022, 9, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2128,
      status: 'Created',
      name: 'Interim 7',
      type: 'Loan/Deposit',
      product: 'DEPO_3',
      amount: 20872.77,
      currency: 'EUR',
      attachments: 4,
      start: new Date(2022, 6, 8),
      term: '6m',
      end: new Date(2022, 12, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 364,
      status: 'Confirmed',
      name: 'JPMC Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '1y',
      end: new Date(2023, 6, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 84634,
      status: 'Created',
      name: 'IC Loan 8',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298926.33,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 7),
      term: '2y',
      end: new Date(2024, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 236,
      status: 'Confirmed',
      name: '2021 IR Swap',
      type: 'IR Swap',
      product: 'IRSWAP_2',
      amount: 94102.0,
      currency: 'EUR',
      attachments: 6,
      start: new Date(2022, 6, 7),
      term: '5y',
      end: new Date(2027, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 6369,
      status: 'Confirmed',
      name: '2021 TLA Actual',
      type: 'Facility Fee',
      product: 'FAC_1',
      amount: 209881.76,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 332,
      status: 'Created',
      name: 'BOFA 19',
      type: 'Loan/Deposit',
      product: 'Loan 4',
      amount: 42.87,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 16664,
      status: 'Submitted',
      name: 'Test deal',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: 1567.08,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '6m',
      end: new Date(2022, 12, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 5429,
      status: 'Confirmed',
      name: 'VAN 2021',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: 18902.74,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 6),
      term: '1y',
      end: new Date(2023, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 4363,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: -278899.27,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 6),
      term: '2y',
      end: new Date(2024, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 526,
      status: 'Confirmed',
      name: 'IC Loan 10',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -10367.89,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 30),
      term: '53',
      end: new Date(2025, 5, 30),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 6236,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'IR Swap',
      product: 'IRSWAP_3',
      amount: 45982.88,
      currency: 'USD',
      attachments: 2,
      start: new Date(2022, 5, 28),
      term: '5y',
      end: new Date(2027, 5, 28),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 722,
      status: 'Created',
      name: 'VAN Borrowing',
      type: 'Loan/Deposit',
      product: 'DEPO_2',
      amount: 300000.00,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 27),
      term: '6m',
      end: new Date(2022, 11, 27),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 35621,
      status: 'Confirmed',
      name: 'TBD',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 12276.29,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 5, 26),
      term: '3m',
      end: new Date(2022, 8, 26),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 5,
      status: 'Confirmed',
      name: 'Test deal',
      type: 'Loan/Deposit',
      product: 'DEPO_MAIN',
      amount: 3637.39,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 5, 24),
      term: '1y',
      end: new Date(2023, 5, 24),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2621,
      status: 'Confirmed',
      name: 'IC Loan 3',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -400993.21,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 18),
      term: '5y',
      end: new Date(2027, 1, 18),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 3285,
      status: 'Created',
      name: 'Interim 5',
      type: 'Loan/Deposit',
      product: 'Loan/D 1',
      amount: 20872.77,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 16),
      term: '1y',
      end: new Date(2023, 6, 16),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 4634,
      status: 'Created',
      name: 'BOFA Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 15),
      term: '5y',
      end: new Date(2027, 6, 15),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 1736,
      status: 'Submitted',
      name: 'IC Loan 2',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298826.33,
      currency: 'USD',
      attachments: 3,
      start: new Date(2022, 6, 14),
      term: '1y',
      end: new Date(2027, 6, 14),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 785,
      status: 'Confirmed',
      name: 'Oil purchase',
      type: 'Loan/Deposit',
      product: 'Loan/D 4',
      amount: 9102.0,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 11),
      term: '2y',
      end: new Date(2024, 6, 11),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 1947,
      status: 'Confirmed',
      name: 'Commitment fee',
      type: 'Facility Fee',
      product: 'FAC122',
      amount: 209881.76,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 10),
      term: '6m',
      end: new Date(2022, 12, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 2632,
      status: 'Confirmed',
      name: '2022 TLA Actual',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 21.99,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 10),
      term: '3m',
      end: new Date(2022, 9, 10),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 841,
      status: 'Submitted',
      name: 'IC Loan 4',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -14298.0,
      currency: 'USD',
      attachments: 8,
      start: new Date(2022, 6, 9),
      term: '5y',
      end: new Date(2027, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 103939,
      status: 'Created',
      name: 'IC Loan 5',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -222000.0,
      currency: 'USD',
      attachments: 11,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 127,
      status: 'Confirmed',
      name: '2022 IR swap',
      type: 'IR Swap',
      product: 'IRSWAP_1',
      amount: -400993.21,
      currency: 'EUR',
      attachments: 3,
      start: new Date(2022, 6, 9),
      term: '2y',
      end: new Date(2024, 6, 9),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 207,
      status: 'Submitted',
      name: 'IC Loan 6',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 2',
      amount: 12391.0,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '3m',
      end: new Date(2022, 9, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 228,
      status: 'Created',
      name: 'Interim 7',
      type: 'Loan/Deposit',
      product: 'DEPO_3',
      amount: 20872.77,
      currency: 'EUR',
      attachments: 4,
      start: new Date(2022, 6, 8),
      term: '6m',
      end: new Date(2022, 12, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 3114,
      status: 'Confirmed',
      name: 'JPMC Borrowing',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: 7002109.33,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 8),
      term: '1y',
      end: new Date(2023, 6, 8),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 8254,
      status: 'Created',
      name: 'IC Loan 8',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: -1298926.33,
      currency: 'USD',
      attachments: 5,
      start: new Date(2022, 6, 7),
      term: '2y',
      end: new Date(2024, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 7420,
      status: 'Confirmed',
      name: '2021 IR Swap',
      type: 'IR Swap',
      product: 'IRSWAP_2',
      amount: 94102.0,
      currency: 'EUR',
      attachments: 6,
      start: new Date(2022, 6, 7),
      term: '5y',
      end: new Date(2027, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 947,
      status: 'Confirmed',
      name: '2021 TLA Actual',
      type: 'Facility Fee',
      product: 'FAC_1',
      amount: 209881.76,
      currency: 'USD',
      attachments: 1,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 200000,
      status: 'Created',
      name: 'BOFA 19',
      type: 'Loan/Deposit',
      product: 'Loan 4',
      amount: 42.87,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '10y',
      end: new Date(2032, 6, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 134,
      status: 'Submitted',
      name: 'Test deal',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 1',
      amount: 1567.08,
      currency: 'EUR',
      attachments: 0,
      start: new Date(2022, 6, 7),
      term: '6m',
      end: new Date(2022, 12, 7),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    },
    {
      id: 293333,
      status: 'Confirmed',
      name: 'VAN 2021',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: 18902.74,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 6, 6),
      term: '1y',
      end: new Date(2023, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 4353,
      status: 'Confirmed',
      name: 'Interim 10',
      type: 'Loan/Deposit',
      product: 'Loan/D 3',
      amount: -278899.27,
      currency: 'EUR',
      attachments: 2,
      start: new Date(2022, 6, 6),
      term: '2y',
      end: new Date(2024, 6, 6),
      rate: '2.0% + 0.50%',
      frequency: 'Monthly'
    },
    {
      id: 5622,
      status: 'Confirmed',
      name: 'IC Loan 10',
      type: 'Intercompany Loan',
      product: 'INTERCO_LOAN 3',
      amount: -10367.89,
      currency: 'USD',
      attachments: 0,
      start: new Date(2022, 5, 30),
      term: '53',
      end: new Date(2025, 5, 30),
      rate: '2.0% + 0.50%',
      frequency: 'Quarterly'
    }
  ];

  // Bind 'this' explicitly to capture the execution context of the component.
  // https://www.telerik.com/kendo-angular-ui/components/grid/export/excel-export/#toc-exporting-specific-data
  constructor(private formBuilder: FormBuilder) {
    this.allData = this.allData.bind(this);
    this.createFormGroup = this.createFormGroup.bind(this);
  }

  // By default, the Grid exports its current data. To export data that is different
  // from the current Grid data, specify a custom fetchData function. It returns an
  // ExcelExportData value or array.
  public allData(): ExcelExportData {
    const result: ExcelExportData = {
      data: process(this.portfolioData, {}).data
    };

    return result;
  }

    // https://www.telerik.com/kendo-angular-ui/components/grid/editing/editing-directives/#toc-in-cell-editing
    public createFormGroup = (args: any): FormGroup => {
      const item = args.dataItem;

      this.formGroup = this.formBuilder.group({
        amount: item.amount,
        start: item.start,
        end: item.end
      });

      return this.formGroup;
    };
}
